### ISSUE TITLE
how are you able to publish to @f scope?

### ISSUE THREAD

**Issue by matthewmueller** [micro-js/position-element#1]
sorry for the noise, wasn't sure how to contact you. curious about the workflow for publishing to @f. did you create an organization on npm?

**Comment by joshrtay** [comment]
We got the username @f from npm. Most of the @[a-z] usernames are just being squatted on, so npm is pretty quick to transfer ownership. When we add people to the organization in git we just give them the @f username and password. 

We have a lot of npm usernames, so we use npmrc to manage them. 

We looked into organizations, but didn't want to pay. This approach has worked pretty well for us.

**Comment by matthewmueller** [comment]
Ah interesting, so it sounds like you can be authenticated to multiple
public registry accounts in your .npmrc. Is that right?

**Comment by ashaffer** [comment]
Ya, we use [npmrc](https://www.npmjs.com/package/npmrc) to manage it. It makes it pretty nice to switch between them. Want to join? :)

**Comment by joshrtay** [comment]
@matthewmueller I couldn't get the support for multiple public registry accounts working in a single .npmrc. Maybe I was doing something wrong.

**Comment by matthewmueller** [comment]
ahh okay great. thanks guys. good to know!

right now i typically publish small libs to the `component/...` org, but i do love the @f npm name :-)
